### PR TITLE
Create home page

### PR DESCRIPTION
**Pull request by stardust2stardust**
- home page based off of wireframe
- links are not active yet
- slider/swiper is not functional yet
- add footer element to root layout

### CODE REVIEW

**Review by damanpr33t — COMMENTED** [review]
The chameleon logo and intro text will be needed to be reused for login page and register page

**Review by hjitiji — DISMISSED** [review]

**Comment by stardust2stardust** [comment]
Good point. I will separate them out into their own components.

**Review by hjitiji — APPROVED** [review]

**Review by damanpr33t — COMMENTED** [review]
On StartSwiperandLinks.tsx, I was thinking that the start image when clicked will go to the register page and only have the login link under so we don't need the create account link. What do you think?

**Comment by stardust2stardust** [comment]
Maybe then the text inside of the start image should say 'Register Now' or 'Create Account' of 'Sign up' or something similar? That way it is clear to the user what clicking either option will lead to. Let me know what you think.

**Comment by damanpr33t** [comment]
yes, that would be ok. Sign Up or Register

**Comment by stardust2stardust** [comment]
Ok cool. I have run out of time for now. I will make the changes either later today or tomorrow.

**Review by Colton923 — APPROVED** [review]
Wow that's some really  clean code. I love seeing just a few classes in a small component. If you have trouble with NextImage let me know.

**Pull request merged**
