### PR TITLE
added navigate components with next/link

### PR DESCRIPTION
**Pull request by damanpr33t**
I made a way to navigate through the pages and components when we click on links using next/link which I think would be easier to use from here on because of less code and easier to write. Let me know what you think if we should use this for everything instead of rendering through useEffect and css.

### CODE REVIEW

**Comment by stardust2stardust** [comment]
I think we might need @Colton923's input on this. This was the way I originally thought we would do it, but I think Colton said we didn't want to create separate pages for displaying the Login and Register forms. Instead, we want to just re-render and display the corresponding component that the user clicks on from the home page.

**Comment by damanpr33t** [comment]
Okay, we will do it that way. I just wanted to make sure what is better practice.

We're you able to do it/are you doing it or should I do it? @stardust2stardust

**Comment by stardust2stardust** [comment]
Hopefully we can get @Colton923's opinion at some point. I don't feel like I'm knowledgeable enough with it to be making decisions lol. And if we do it without using the Link way, then I think PR#17 has done a little bit of it already.

**Review by Colton923 — APPROVED** [review]
I'm cool with Links pushing someone to the login page, rather than overlaying the '/' (index) page with a login component. Whatever you want the UIUX to be is cool with me.

**Pull request closed without merging**
