### PR TITLE
global background style

### PR DESCRIPTION
**Pull request by damanpr33t**
instead of creating a background component, just applied background styling to root layout for global use

### CODE REVIEW

**Review by stardust2stardust — APPROVED** [review]
We will have variables for colors soon.

**Comment by hjitiji** [comment]
@Colton923 was the one who specifically mentioned this being a component. Will wait for him to chime in as to the benefits of doing it as a component before we merge this PR. I dont know any React to speak intelligently on the topic - if someone else does feel free to chime in.

**Comment by stardust2stardust** [comment]
Are we still needing to get @Colton923's opinion on this?

**Comment by Colton923** [comment]
This is fine for now. Eventually I'm sure we will have a more complicated background if we get time. If we want a parallax effect, and anything outside of a gradient or whatever then a background component eventually.

**Review by Colton923 — APPROVED** [review]

**Pull request merged**
